services:
  mongodb:
    image: mongo:8.3.7
    container_name: mongodb_local
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
